# Generated by Django 5.2.9 on 2026-02-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lidarupload',
            options={'managed': True, 'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='lidarupload',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='lidarupload',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='lidarupload',
            name='progress_step',
        ),
        migrations.RemoveField(
            model_name='lidarupload',
            name='status',
        ),
        migrations.AddField(
            model_name='lidarupload',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lidarupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lidarupload',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lidar_uploads', to='stations.station'),
        ),
        migrations.CreateModel(
            name='LidarDTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('progress_step', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('laz_count', models.IntegerField(default=0, help_text='Nombre de LAZ fusionnés')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lidar_dtm', to='stations.station')),
            ],
            options={
                'db_table': 'lidar_dtm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LidarSnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'Aucun'), ('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='none', max_length=20)),
                ('progress_step', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('base_snow_cm', models.FloatField(blank=True, help_text='Hauteur de neige de référence utilisée (depuis Open-Meteo)', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lidar_snow', to='stations.station')),
            ],
            options={
                'db_table': 'lidar_snow',
                'managed': True,
            },
        ),
    ]
