# Generated by Django 5.2.6 on 2025-09-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piste',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'managed': False},
        ),
    ]
