# Generated by Django 5.2.6 on 2025-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_piste_options_alter_station_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowMeasure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField(db_column='date_heure')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitations_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hauteur_neige_totale_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hauteur_neige_naturelle_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hauteur_neige_artificielle_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('production_neige_artificielle_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'snow_measures',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='piste',
            table='pistes',
        ),
        migrations.AlterModelTable(
            name='station',
            table='stations',
        ),
    ]
